// vue-sample_old/pages/ColorList1.vue
<template>
  <div>
    <button @click="setColor('Red')">Red</button>
    <button @click="setColor('Blue')">Blue</button>
    <button @click="setColor('Green')">Green</button>
    <span>Color is: <strong>{{ selectedColor }}</strong></span>
  </div>
</template>

<script>
export default {
  name: 'ColorList1',
  methods: {
    setColor (color) {
      this.selectedColor = color
    }
  },
  data () {
    return {
      selectedColor: ''
    }
  }
}
</script>

// svelte-sample/src/routes/colorList1.svelte
<script>
  let selectedColor = '';
  
  function setColor(color) {
    selectedColor = color;
  }
</script>

<button on:click="{() => setColor('red')}">red</button>
<button on:click="{() => setColor('blue')}">blue</button>
<button on:click="{() => setColor('green')}">green</button>
<span>Color is: <strong>{selectedColor}</strong></span>
