// react-sample/pages/helloWorld.js
import React, { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)
  const [name, setName] = useState('World')

  function incrementCount() {
    setCount(count + 1)
  }

  function nameChange(event) {
    setName(event.target.value)
  }

  return (
    <div className="App">
      <h1>Hello {name}!</h1>
      <input type="text" value={name} onInput={nameChange} />
      <button onClick={incrementCount}>Clicks: {count}</button>
    </div>
  );
}

// svelte-sample/src/routes/helloWorld.svelte
<!-- Version 1 -->
<script>
  let name = 'World'
  let count = 0
 
  function nameChange(event) {
    name = event.target.value
  }
 
  function incrementCount() {
    count += 1
  }
</script>

<h1>Hello {name}!</h1>
<input type="text" value="{name}" on:input={nameChange} />
<button on:click="{incrementCount}">Clicks: {count}</button>

<!-- Version 2 -->
<!-- <script>
  $: name = 'World'
  let count = 0
</script>

<h1>Hello {name}!</h1>
<input type="text" bind:value="{name}" />
<button on:click="{() => count += 1}">Clicks: {count}</button> -->
