// svelte-sample/src/routes/colorList2.svelte
<script>
  let colors = ['red', 'blue', 'green'];
  let selectedColor = '';
  
  function setColor(color) {
    selectedColor = color;
  }
</script>

{#each colors as color}
  <button on:click="{() => setColor(color)}">{color}</button>
{/each}
<span>Color is: <strong>{selectedColor}</strong></span>

<br/>
{#if !selectedColor}
  <span>Pick a color!</span>
{:else if selectedColor === 'red'}
  <span>That's my favorite color!</span>
{:else}
  <span>That's almost as cool as red!</span>
{/if}

// vue-sample/pages/ColorList2.vue
<template>
  <div>
    <button v-for="color in colors" :key="color" @click="setColor(color)">{{ color }}</button>
    <span>Color is: <strong>{{ selectedColor }}</strong></span>

    <span class="d-block mt-2" v-if="!selectedColor">Pick a color!</span>
    <span class="d-block mt-2" v-else-if="selectedColor === 'red'">That's my favorite color!</span>
    <span class="d-block mt-2" v-else>That's almost as cool as red!</span>
  </div>
</template>

<script>
export default {
  name: 'ColorList2',
  methods: {
    setColor (color) {
      this.selectedColor = color
    }
  },
  data () {
    return {
      colors: ['red', 'blue', 'green'],
      selectedColor: ''
    }
  }
}
</script>
