// svelte-sample/src/routes/helloWorld.svelte
<!-- Version 1 -->
<script>
  let name = 'World'
  let count = 0
 
  function nameChange(event) {
    name = event.target.value
  }
 
  function incrementCount() {
    count += 1
  }
</script>

<h1>Hello {name}!</h1>
<input type="text" value="{name}" on:input={nameChange} />
<button on:click="{incrementCount}">Clicks: {count}</button>

<!-- Version 2 -->
<!-- <script>
  $: name = 'World'
  let count = 0
</script>

<h1>Hello {name}!</h1>
<input type="text" bind:value="{name}" />
<button on:click="{() => count += 1}">Clicks: {count}</button> -->

// vue-sample/pages/helloWorld.vue
<template>
  <div>
    <h1>Hello {{ name }}!</h1>
    <input type="text" v-model="name" />
    <button @click="incrementCount">Clicks: {{ count }}</button>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  methods: {
    incrementCount () {
      this.count++
    }
  },
  data () {
    return {
      name: 'World',
      count: 0
    }
  }
}
</script>
