// vue-sample/pages/ColorList1.vue
<template>
  <div>
    <button @click="setColor('red')">red</button>
    <button @click="setColor('blue')">blue</button>
    <button @click="setColor('green')">green</button>
    <span>Color is: <strong>{{ selectedColor }}</strong></span>
  </div>
</template>

<script>
export default {
  name: 'ColorList1',
  methods: {
    setColor (color) {
      this.selectedColor = color
    }
  },
  data () {
    return {
      selectedColor: ''
    }
  }
}
</script>

// svelte-sample_old/src/routes/colorList1.svelte
<script>
  let selectedColor = ''
  
  function setColor(color) {
    selectedColor = color
  }
</script>

<button on:click="{() => setColor('Red')}">Red</button>
<button on:click="{() => setColor('Blue')}">Blue</button>
<button on:click="{() => setColor('Green')}">Green</button>
<span>Color is: <strong>{selectedColor}</strong></span>
