// svelte-sample/src/routes/todoList.svelte
<script>
  let todos = [
		{ done: false, text: 'Eat' },
    { done: false, text: 'Sleep' },
    { done: false, text: 'Learn Svelte' },
    { done: false, text: 'Repeat' }
	];
	
	function toggleDone(t) {
		todos = todos.map(todo => {
			if (todo === t) return { done: !t.done, text: t.text };
			return todo;
		});
	}
	
	let hideDone = false;
	
	$: showing = filtered.length;
	
	$: filtered = hideDone
		? todos.filter(todo => !todo.done)
		: todos;
</script>

<label>
	<input type="checkbox" bind:checked={hideDone}>
	Hide Done
</label>

<span>Showing {showing} of {todos.length}</span>

<ul>
	{#each filtered as todo}
		<li on:click={() => toggleDone(todo)}>
			{todo.done ? 'X' : ''} {todo.text}
		</li>
	{/each}
</ul>

// react-sample/pages/todoList.js
import React, { useState } from 'react'

export default function TodoList() {
  const [todos, setTodos] = useState([
    { done: false, text: 'Eat' },
    { done: false, text: 'Sleep' },
    { done: false, text: 'Learn Svelte' },
    { done: false, text: 'Repeat' }
  ])

  function toggleDone(t) {
    setTodos(todos.map(todo => {
      if (todo === t) return { done: !t.done, text: t.text }
      return todo
    }))
  }

  const [hideDone, setHideDone] = useState(false)

  function toggleHideDone() {
    setHideDone(!hideDone)
  }

  const filtered = hideDone
    ? todos.filter(todo => !todo.done)
    : todos

  return (
    <div>
      <label>
        <input type="checkbox" class="me-1" checked={hideDone} onChange={toggleHideDone} />
        Hide Done - Showing {filtered.length} of {todos.length}
      </label>

      <ul>
        {filtered.map(todo => (
          <li onClick={() => toggleDone(todo)}>
            {todo.done ? 'X' : ''} {todo.text}
          </li>
        ))}
      </ul>
    </div>
  );
}
